# Generated by Django 6.0 on 2025-12-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_doctorprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
